version: "3"
services:
  php:
    build:
      context: ./php
    container_name: dal-php
    volumes:
      - ./:/var/www/html
      # - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      # - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    image: dal-php
    networks:
      - dal-network

  mysql:
    image: mysql:latest
    container_name: dal-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "R00T"
      MYSQL_DATABASE: "dal"
    volumes:
      - cms-api-mysql:/var/lib/mysql
    ports:
      - 3310:3306
    networks:
      - dal-network

  nginx:
    image: nginx:alpine
    container_name: dal-nginx
    ports:
      - 8810:80
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dal-network
    depends_on:
      - php
      - mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: dal-phpmyadmin
    restart: unless-stopped
    ports:
      - 3001:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 100000000
    networks:
      - dal-network
    depends_on:
      - mysql
networks:
  dal-network:


volumes:
  cms-api-mysql:


